// flow-typed signature: e131221e3c72659be12a3ef6dfa76bc8
// flow-typed version: <<STUB>>/jest-immutable-matchers_v^1.5.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-immutable-matchers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-immutable-matchers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-immutable-matchers/dist/jest-immutable-matchers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-immutable-matchers/dist/jest-immutable-matchers.js' {
  declare module.exports: $Exports<'jest-immutable-matchers/dist/jest-immutable-matchers'>;
}
declare module 'jest-immutable-matchers/index' {
  declare module.exports: $Exports<'jest-immutable-matchers'>;
}
declare module 'jest-immutable-matchers/index.js' {
  declare module.exports: $Exports<'jest-immutable-matchers'>;
}
